set(CXX_FILES
	src/c++/Core/Config.cpp
	src/c++/Core/Config.hpp
	src/c++/Core/Core.cpp
	src/c++/Core/Core.hpp
	src/c++/Core/Event/Event.cpp
	src/c++/Core/Event/Event.hpp
	src/c++/Core/Event/EventHandler.hpp
	src/c++/Core/Locale/Locale.hpp
	src/c++/Core/Locale/LocaleManager.cpp
	src/c++/Core/Locale/LocaleManager.hpp
	src/c++/Core/Locale/LocalePackage.cpp
	src/c++/Core/Locale/LocalePackage.hpp
	src/c++/Core/Locale/LocaleStrings.hpp
	src/c++/Core/Menu/Items/ItemForm.hpp
	src/c++/Core/Menu/Items/ItemPlugin.hpp
	src/c++/Core/Menu/PluginExplorer.cpp
	src/c++/Core/Menu/PluginExplorer.hpp
	src/c++/Core/Menu/PluginExplorerHandler.cpp
	src/c++/Core/Menu/PluginExplorerHandler.hpp
	src/c++/Core/Menu/PluginExplorerMenu.cpp
	src/c++/Core/Menu/PluginExplorerMenu.hpp
	src/c++/Core/Menu/StartMenu.cpp
	src/c++/Core/Menu/StartMenu.hpp
	src/c++/General/Input.hpp
	src/c++/General/Script.hpp
	src/c++/General/Singleton.hpp
	src/c++/General/Skyrim.hpp
	src/c++/Main.cpp
	src/c++/PCH.hpp
	src/c++/Scaleform/CLIK/Array.hpp
	src/c++/Scaleform/CLIK/GFx/Controls/Button.hpp
	src/c++/Scaleform/CLIK/GFx/Controls/ButtonBar.hpp
	src/c++/Scaleform/CLIK/GFx/Controls/CoreList.hpp
	src/c++/Scaleform/CLIK/GFx/Controls/DropdownMenu.hpp
	src/c++/Scaleform/CLIK/GFx/Controls/ScrollingList.hpp
	src/c++/Scaleform/CLIK/GFx/Controls/Slider.hpp
	src/c++/Scaleform/CLIK/GFx/Controls/TextInput.hpp
	src/c++/Scaleform/CLIK/GFx/Core/UIComponent.hpp
	src/c++/Scaleform/CLIK/MovieClip.hpp
	src/c++/Scaleform/CLIK/Object.hpp
	src/c++/Scaleform/CLIK/TextField.hpp
	src/c++/Scaleform/Common/ItemList.hpp
	src/c++/Scaleform/System/Function.hpp
	src/c++/Scaleform/System/Logger.hpp
)
