set(CXX_FILES
	src/c++/Event/Event.cpp
	src/c++/Event/Event.h
	src/c++/Event/EventHandler.h
	src/c++/Event/Input.h
	src/c++/Menus/Menus.cpp
	src/c++/Menus/Menus.h
	src/c++/Menus/PluginExplorer/Items/ItemForm.h
	src/c++/Menus/PluginExplorer/Items/ItemPlugin.h
	src/c++/Menus/PluginExplorer/PluginExplorer.cpp
	src/c++/Menus/PluginExplorer/PluginExplorer.h
	src/c++/Menus/PluginExplorer/PluginExplorerHandler.cpp
	src/c++/Menus/PluginExplorer/PluginExplorerHandler.h
	src/c++/Menus/PluginExplorer/PluginExplorerMenu.cpp
	src/c++/Menus/PluginExplorer/PluginExplorerMenu.h
	src/c++/Menus/Start/Start.cpp
	src/c++/Menus/Start/Start.h
	src/c++/PCH.h
	src/c++/REX/REX.cpp
	src/c++/REX/REX.h
	src/c++/Scaleform/CLIK/Array.h
	src/c++/Scaleform/CLIK/GFx/Controls/Button.h
	src/c++/Scaleform/CLIK/GFx/Controls/ButtonBar.h
	src/c++/Scaleform/CLIK/GFx/Controls/CoreList.h
	src/c++/Scaleform/CLIK/GFx/Controls/DropdownMenu.h
	src/c++/Scaleform/CLIK/GFx/Controls/ScrollingList.h
	src/c++/Scaleform/CLIK/GFx/Controls/Slider.h
	src/c++/Scaleform/CLIK/GFx/Controls/TextInput.h
	src/c++/Scaleform/CLIK/GFx/Core/UIComponent.h
	src/c++/Scaleform/CLIK/MovieClip.h
	src/c++/Scaleform/CLIK/Object.h
	src/c++/Scaleform/CLIK/TextField.h
	src/c++/Scaleform/Common/ItemList.h
	src/c++/Scaleform/System/Function.h
	src/c++/Scaleform/System/Logger.h
	src/c++/Script/Script.h
	src/c++/Settings.h
	src/c++/main.cpp
)
